name = "GeneralMetadata"
uuid = "4a600115-d4d8-4abf-a446-0aa1ef6151e0"
authors = ["Matt Bauman <mbauman@juliahub.com>", "and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.0"
DataStructures = "0.19.1"
Dates = "1.11.0"
HTTP = "1.10.17"
JSON3 = "1.14.3"
Statistics = "1.11.1"
StatsBase = "0.34.6"
TOML = "1.0.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
